# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77ce4abf89135c5e15e070367b6d7e96621f33d39d0c85c44612f70803055025a0946788dea3cb6549b7de2520517b60bb90b6ba986be413403ab454a112f896

test:
  secret_key_base: 2932200612255b77e164dc40e8c41aa84d278e2640d11ceee4913e65b66ce148954a715690e46e313b5df20fb9263f5b0e54a426168e619c47ef10c1cf6a4dd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
